blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogPostCreateView,
    BlogPostListView,
    BlogPostDetailView,
    BlogPostUpdateView,
    BLogPostDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogPostListView.as_view(), name="list"),
    path("create/", BlogPostCreateView.as_view(), name="create"),
    path("view/<int:pk>/", BlogPostDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogPostUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BLogPostDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

NULLABLE = {"null": True, "blank": True}


class BlogPost(models.Model):
    """Модель блоговой записи"""

    title = models.CharField(max_length=150, verbose_name="заголовок")
    content = models.TextField(verbose_name="содержимое")
    preview = models.ImageField(**NULLABLE, verbose_name="изображение")
    creation_date = models.DateField(
        default=datetime.date.today().isoformat(),
        **NULLABLE,
        verbose_name="дата создания"
    )
    #  Признак публикации
    publication_sign = models.BooleanField(default=False, verbose_name="опубликовано")
    views = models.IntegerField(default=0, verbose_name="колличество просмотров")
    slug = models.CharField(max_length=150, verbose_name="slug", null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "запись"
        verbose_name_plural = "записи"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from pytils.translit import slugify

from blog.models import BlogPost


class BlogPostCreateView(CreateView):
    """Создание блога"""

    model = BlogPost
    fields = ("title", "content", "creation_date", "publication_sign", "views")
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        """Создание динамического slug"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
            return super().form_valid(form)


class BlogPostUpdateView(UpdateView):
    """Обновление блога"""

    model = BlogPost
    fields = ("title", "content", "creation_date", "publication_sign", "views")

    def get_success_url(self):
        """Перенаправление после редактирования на просмотр блога"""
        return reverse("blog:view", args=[self.kwargs.get("pk")])


class BlogPostListView(LoginRequiredMixin, ListView):
    """Для страницы с блогами"""

    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        """Метод для вывода только тех блогов, где подтверждена публикация"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_sign=True)
        return queryset


class BlogPostDetailView(DetailView):
    """Для подробного описания блога"""

    model = BlogPost

    def get_object(self, queryset=None):
        """Метод для увеличения счетчика просмотров"""
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BLogPostDeleteView(DeleteView):
    """Для удаления блога"""

    model = BlogPost
    success_url = reverse_lazy("blog:list")

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить пост?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h4 class="my-0 font-weight-normal">"{{object.title|title}}" ({{object.slug}})</h4>
            </div>
            <div class="card-body">
                <p class="text-left">{{object.content}}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% if object.preview %}
                    <img class="card-img-top" src="{{ object.preview|forblog }}"
                         alt="Card image cap">
                    {% endif %}
                    <li>создано:{{object.creation_date}}</li>
                    <li>просмотры:{{object.views}}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object %}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    {% else %}
                    <button type="submit" class="btn btn-success">Опубликовать</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-3 mb-5 mx-auto">
        <a href="{% url 'blog:create' %}" type="button"
           class="btn btn-lg btn-block btn-outline-primary">Добавить блог</a>
    </div>
</div>
<div class="row text-center mx-auto">
    {% for object in object_list %}
    <div class="col-3 mb-5">
        <div class="card mb-4 box-shadow mb-md-3">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.title|title}}</h4>
            </div>
            <a href="{% url 'blog:view' object.pk %}" type="button"
               class="btn btn-sm btn-block btn-outline-warning">Перейти</a>
            <a href="{% url 'blog:edit' object.pk %}" type="button"
               class="btn btn-sm btn-block btn-outline-success">Обновить</a>
            <a href="{% url 'blog:delete' object.pk %}" type="button"
               class="btn btn-sm btn-block btn-outline-danger">Удалить</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}