blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogPostCreateView,
    BlogPostListView,
    BlogPostDetailView,
    BlogPostUpdateView,
    BLogPostDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogPostListView.as_view(), name="list"),
    path("create/", BlogPostCreateView.as_view(), name="create"),
    path("view/<int:pk>/", BlogPostDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogPostUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BLogPostDeleteView.as_view(), name="delete"),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (
    ContactsView,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name


urlpatterns = [
    path("", ProductListView.as_view(), name="home"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_details"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "products/update/<int:pk>/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    RegisterView,
    ProfileView,
    generate_password,
    activate_user,
    congratulations,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/genpassword/", generate_password, name="generate_password"),
    path("activate/<uuid:uid>", activate_user, name="activate_user"),
    path("congratulations/", congratulations, name="congratulations"),
]

users/models.py
from uuid import uuid4

from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {"null": True, "blank": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="почта")

    phone = models.CharField(max_length=35, verbose_name="телефон", **NULLABLE)
    avatar = models.ImageField(upload_to="users/", verbose_name="аватар", **NULLABLE)
    country = models.CharField(max_length=150, verbose_name="страна", **NULLABLE)
    activate_token = models.UUIDField(default=uuid4, **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import BooleanField
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = (
            "email",
            "password1",
            "password2",
        )
        model.is_active = False


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = (
            "email",
            "password",
            "first_name",
            "last_name",
            "country",
            "phone",
            "avatar",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    """Контроллер для регистрации нового пользователя"""

    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        """Отправка сообщения на почту"""
        new_user = form.save()
        # после регистрации is_active устанавливается в False (по дефолту он стоит в True)
        new_user.is_active = False
        # НЕ забыть сохранить изменения в модели
        new_user.save()
        url = reverse("users:activate_user", kwargs={"uid": new_user.activate_token})
        msg = f"для активации перейдите по ссылке: http://127.0.0.1:8000{url}"
        print(msg)
        send_mail(
            subject="Ку-ку!",
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user],
        )
        return super().form_valid(form)


def activate_user(request, uid):
    """Активация профиля по полученной ссылке"""
    model = User.objects.get(activate_token=uid)
    #  после подтверждения регистрации is_active выставляем в True
    model.is_active = True
    model.save()
    return redirect("users:congratulations")


def congratulations(request):
    """Контроллер для отправки поздравления с регистрацией"""
    return render(request, "users/congratulations.html")


class ProfileView(UpdateView):
    """Редактирование профиля"""

    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


def generate_password(request):
    """Генерация рандомного пароля"""
    new_password = [str(random.randint(0, 9)) for _ in range(6)]
    letters = [str(random.choice([chr(i) for i in range(97, 123)])) for _ in range(6)]
    new_password.extend(letters)
    random.shuffle(new_password)
    new_password = "".join(new_password)

    send_mail(
        subject="Смена пароля",
        message=f"Ваш новый пароль: {new_password}",
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse("catalog:home"))

users/templates/users/congratulations.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row ">
        <div class="col-5 col-md-6 mx-auto">
            <div class="card">
                <div class="card-header mx-auto">
                    <h1>Поздравляем!</h1>
                    <h2>Вы зарегистрированы!</h2>
                </div>
                <div class="card-body mx-auto">
                    <a href="{% url 'catalog:home' %}" class="btn btn-success">Перейти на главную</a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row ">
        <div class="col-5 col-md-6 mx-auto">
            <div class="card">
                <div class="card-header ">
                    <h1>Вход</h1>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        Войти
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row ">
        <div class="col-5 col-md-6 mx-auto">
            <div class="card">
                <div class="card-header ">
                    <h1>Регистрация</h1>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        Зарегистрироваться
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row ">
        <div class="col-5 col-md-6 mx-auto">
            <div class="card">
                <div class="card-header ">
                    <h1>Профиль</h1>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        Сохранить
                    </button>
                </div>
                <div class ="card-footer">
                    <a href="{% url 'users:generate_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}