blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogPostCreateView,
    BlogPostListView,
    BlogPostDetailView,
    BlogPostUpdateView,
    BLogPostDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogPostListView.as_view(), name="list"),
    path("create/", BlogPostCreateView.as_view(), name="create"),
    path("view/<int:pk>/", BlogPostDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogPostUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BLogPostDeleteView.as_view(), name="delete"),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (
    ContactsView,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name


urlpatterns = [
    path("", ProductListView.as_view(), name="home"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_details"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "products/update/<int:pk>/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "products/delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="наименование")
    description = models.TextField(max_length=100, verbose_name="описание")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ("name",)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="название товара")
    description = models.TextField(verbose_name="описание товара")
    preview = models.ImageField(
        upload_to="products/", verbose_name="изображение", **NULLABLE
    )
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        **NULLABLE,
        verbose_name="продавец",
        help_text="укажите продавца",
    )

    price = models.IntegerField(verbose_name="цена товара")
    created_at = models.DateTimeField(auto_now=True, verbose_name="дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="дата обновления")

    def __str__(self):
        return f"{self.name}: {self.description}"

    class Meta:
        verbose_name = "подукт"
        verbose_name_plural = "продукты"
        ordering = (
            "name",
            "description",
        )


class Version(models.Model):
    """Модель версий"""

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="versions", verbose_name="товар"
    )
    version_number = models.IntegerField(verbose_name="номер версии")
    version_name = models.CharField(max_length=150, verbose_name="название версии")
    active = models.BooleanField(default=True, verbose_name="признак текущей версии")

    def __str__(self):
        return self.version_name

    class Meta:
        verbose_name = "версия"
        verbose_name_plural = "версии"

catalog/forms.py
from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def clean_sample(self, model_attribute: str, attribute_name: str):
        """Метод для избежания дублирования кода в clean_.."""
        cleaned_data = self.cleaned_data[model_attribute]
        forbidden_words = [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        if cleaned_data.lower() in forbidden_words:
            raise forms.ValidationError(
                f"В {attribute_name} присудствуют запрещенные слова!"
            )
        return cleaned_data

    def clean_name(self):
        """Проверка названия товара"""
        cleaned_data = self.clean_sample("name", "названии")
        return cleaned_data

    def clean_description(self):
        """Проверка описания товара"""
        cleaned_data = self.clean_sample("description", "описании")
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    UpdateView,
    DeleteView,
)

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Category, Version


class ContactsView(LoginRequiredMixin, TemplateView):
    """Недописан"""

    template_name = "catalog/contacts.html"
    extra_context = {
        "title": "Контакты",
        "description": "Заполните форму, и мы с вами свяжемся",
    }

    def post(self, request):
        """в TemplateView есть только метод get, поэтому post прописан вручную"""
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"{name} ({phone}): {message}")

        return render(request, self.template_name)


class ProductListView(LoginRequiredMixin, ListView):
    """Для главной страницы"""

    model = Product
    extra_context = {
        "title": "Store",
        "description": "Это магазин разных товаров",
    }


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Для подробного описания товара"""

    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        """Привязать пользователя к продукту"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:home")


# FBV------------------------------------------------------------------------------------------------------------------
# def contacts(request):
#     context = {
#         'title': 'Контакты',
#         'description': 'Заполните форму, и мы с вами свяжемся'
#     }
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         print(f'{name} ({phone}): {message}')
#
#     return render(request, 'catalog/contacts.html', context)


# def home(request):
#     context = {
#         'product_list': Product.objects.all(),
#         'title': 'Store',
#         'description': 'Это магазин разных товаров'
#     }
#
#     return render(request, 'catalog/home.html', context)


# def product_details(request, pk):
#     context = {
#         'product': Product.objects.get(pk=pk),
#         'title': 'Подробное описание товара',
#         'description': 'Все, что вам нужно знать о товаре'
#     }
#     return render(request, 'catalog/details.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Store</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{title}}</h1>
    <p class="lead">{{description}}</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Контактный телефон" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/details.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h4 class="my-0 font-weight-normal">{{product.name|title}}</h4>
            </div>
            <div class="card-body text-center">
                <h1 class="card-title pricing-card-title">{{product.price}}р.</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <img class="card-img-top" src="{{ product.preview|mymedia }}"
             alt="Card image cap">
                    <li>- {{product.category|title}}</li>
                    <li>- {{product.description}}</li>
                    <li>- создано:{{product.created_at}}</li>
                    <li>- изменено:{{product.updated_at}}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    {% for product in product_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{product.name|title}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% if product.description|length >= 100 %}
                    <li>- {{product.description|slice:100}}...</li>
                    {% else %}
                    <li>- {{product.description}}</li>
                    {% endif %}
                </ul>
                <a href="{% url 'catalog:product_details' product.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Перейти к товару</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="rov">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                Удаление
            </div>
            <div class="card-body">

                {% csrf_token %}
                <p>Хотите удалить продукт {{ object.name }}?</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a href="{% url 'catalog:home' %}" type="button" class="btn btn btn-outline-warning">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="row">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header text-center">
                <h4 class="my-0 font-weight-normal">{{object.name|title}}</h4>
            </div>
            <div class="card-body text-center">
                <h1 class="card-title pricing-card-title">{{object.price}}р.</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <img class="card-img-top" src="{{ object.preview|mymedia }}"
                         alt="Card image cap">
                    <li>- {{object.category|title}}</li>
                    <li>- {{object.description}}</li>
                    <li>- создано:{{object.created_at}}</li>
                    <li>- изменено:{{object.updated_at}}</li>
                    <li>- продавец:{{object.user}}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
<div class="row ">
    <div class="col-sm-5 col-md-6">
        <div class="card">
            <div class="card-header">
                Добавление продукта в каталог
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    Добавить
                </button>
            </div>
        </div>
    </div>
    <div class="col-sm-5 col-md-6">
        <div class="card">
            <div class="card-header">
                Добавление версии продукта
            </div>
            <div class="card-body">
               {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-success" href="{% url 'catalog:product_create' %}">Добавить товар</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.name|title}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% if object.description|length >= 100 %}
                    <li>- {{object.description|slice:100}}...</li>
                    {% else %}
                    <li>- {{object.description}}</li>
                    {% endif %}
                </ul>
                {% if object.versions.all %}
                {% for version in object.versions.all %}
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% if version.active %}
                    <li> Название версии: {{version.version_name}}</li>
                    <li> Номер версии: {{version.version_number}}</li>
                    {% endif %}
                </ul>
                {% endfor %}
                 {% else %}
                    <li> Нет активной версии </li>
                {% endif %}
                <a href="{% url 'catalog:product_details' object.pk %}" type="button"
                   class="btn btn-sm btn-block btn-outline-success">Перейти к товару</a>
                <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                   class="btn btn-sm btn-block btn-outline-primary">Добавить версию/Изменить</a>
                <a href="{% url 'catalog:product_delete' object.pk %}" type="button"
                   class="btn btn-sm btn-block btn-outline-danger">Удалить товар</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}